#!/usr/bin/env bash
# Read the deployed CloudFormation stack Outputs and write frontend/.env.local for the SPA.
# Usage: scripts/write-frontend-env.sh <stack-name> [region]
set -euo pipefail

STACK_NAME="${1:?usage: write-frontend-env.sh <stack-name> [region]}"
REGION="${2:-us-east-1}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/frontend/.env.local"

output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

POOL_ID="$(output CognitoUserPoolId)"
CLIENT_ID="$(output CognitoUserPoolClientId)"
DOMAIN="$(output CognitoHostedDomain)"
API_BASE="$(output ApiGatewayBaseUrl)"

if [[ -z "$POOL_ID" || "$POOL_ID" == "None" ]]; then
  echo "Could not read stack Outputs for '$STACK_NAME' in '$REGION'. Is it deployed?" >&2
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/write-frontend-env.sh from stack '${STACK_NAME}' — do not commit.
VITE_COGNITO_AUTHORITY=https://cognito-idp.${REGION}.amazonaws.com/${POOL_ID}
VITE_COGNITO_CLIENT_ID=${CLIENT_ID}
VITE_COGNITO_DOMAIN=${DOMAIN}
VITE_API_BASE_URL=${API_BASE}
VITE_REDIRECT_URI=http://localhost:5173
EOF

echo "Wrote ${ENV_FILE}:"
sed 's/^/  /' "$ENV_FILE"
