#!/usr/bin/env bash
# Read the deployed CloudFormation stack Outputs and write the SPA's Vite env files:
#   frontend/.env.local            — local dev (`npm run dev`): redirect URI = localhost:5173
#   frontend/.env.production.local — production build (`npm run build`): redirect URI = CloudFront
# Vite precedence loads .env.production.local over .env.local for `build`, and ignores it for
# `dev`, so the same deployed API/Cognito values serve both while each mode gets its own redirect.
# Usage: scripts/write-frontend-env.sh <stack-name> [region]
set -euo pipefail

STACK_NAME="${1:?usage: write-frontend-env.sh <stack-name> [region]}"
REGION="${2:-us-east-1}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/frontend/.env.local"
PROD_ENV_FILE="${REPO_ROOT}/frontend/.env.production.local"

output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

POOL_ID="$(output CognitoUserPoolId)"
CLIENT_ID="$(output CognitoUserPoolClientId)"
DOMAIN="$(output CognitoHostedDomain)"
API_BASE="$(output ApiGatewayBaseUrl)"
CLOUDFRONT_URL="$(output CloudFrontUrl)"

if [[ -z "$POOL_ID" || "$POOL_ID" == "None" ]]; then
  echo "Could not read stack Outputs for '$STACK_NAME' in '$REGION'. Is it deployed?" >&2
  exit 1
fi

# Shared block — everything except the redirect URI, which differs per mode.
shared_env() {
  cat <<EOF
# Generated by scripts/write-frontend-env.sh from stack '${STACK_NAME}' — do not commit.
VITE_COGNITO_AUTHORITY=https://cognito-idp.${REGION}.amazonaws.com/${POOL_ID}
VITE_COGNITO_CLIENT_ID=${CLIENT_ID}
VITE_COGNITO_DOMAIN=${DOMAIN}
VITE_API_BASE_URL=${API_BASE}
EOF
}

{ shared_env; echo "VITE_REDIRECT_URI=http://localhost:5173"; } > "$ENV_FILE"
echo "Wrote ${ENV_FILE}:"
sed 's/^/  /' "$ENV_FILE"

if [[ -n "$CLOUDFRONT_URL" && "$CLOUDFRONT_URL" != "None" ]]; then
  { shared_env; echo "VITE_REDIRECT_URI=${CLOUDFRONT_URL}"; } > "$PROD_ENV_FILE"
  echo "Wrote ${PROD_ENV_FILE}:"
  sed 's/^/  /' "$PROD_ENV_FILE"
else
  echo "No CloudFrontUrl output found — skipped ${PROD_ENV_FILE} (hosting not deployed?)." >&2
fi
